name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish for Windows
      run: dotnet publish -r win-x64 -c ReleaseComplete /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Publish for Linux
      run: dotnet publish -r linux-x64 --configuration ReleaseComplete
    - name: Upload Artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: bussiness_api_test
        path: bin/ReleaseComplete/net6.0/win-x64/publish/bussiness_api_test.exe
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/dotnettest:latest .
    - name: Upload container to Docker Hub with Push
      run: docker push ${{ secrets.DOCKER_USER }}/dotnettest:latest
